### ISSUE TITLE
Create Issues from Roadmap

### ISSUE THREAD

**Issue by erichardson-lee** [erichardson-lee/MQTT.ts#3]
## Roadmap to 1.0

- [ ] finish API docs
- [ ] protocol version 3.1
- [ ] mqtts for deno and node clients
- [ ] use native event target/emitter classes
- [ ] events for messages matching topic filters
- [ ] async iterators for messages matching topic filters
- [ ] make disconnect wait until all publishes sent/acknowledged
- [ ] #4

## Post 1.0

- [ ] protocol version 5.0
- [ ] round robin connect to multiple brokers
- [ ] benchmarking and performance improvements
- [ ] MQTT over QUIC
- [ ] base class for server applications?
